import fs from "fs";

var SyntaxKind = /* @__PURE__ */ ((SyntaxKind5) => {
    SyntaxKind5[SyntaxKind5["Unknown"] = 0] = "Unknown";
    SyntaxKind5[SyntaxKind5["EndOfFileToken"] = 1] = "EndOfFileToken";
    SyntaxKind5[SyntaxKind5["SingleLineCommentTrivia"] = 2] = "SingleLineCommentTrivia";
    SyntaxKind5[SyntaxKind5["MultiLineCommentTrivia"] = 3] = "MultiLineCommentTrivia";
    SyntaxKind5[SyntaxKind5["NewLineTrivia"] = 4] = "NewLineTrivia";
    SyntaxKind5[SyntaxKind5["WhitespaceTrivia"] = 5] = "WhitespaceTrivia";
    SyntaxKind5[SyntaxKind5["ShebangTrivia"] = 6] = "ShebangTrivia";
    SyntaxKind5[SyntaxKind5["ConflictMarkerTrivia"] = 7] = "ConflictMarkerTrivia";
    SyntaxKind5[SyntaxKind5["NonTextFileMarkerTrivia"] = 8] = "NonTextFileMarkerTrivia";
    SyntaxKind5[SyntaxKind5["NumericLiteral"] = 9] = "NumericLiteral";
    SyntaxKind5[SyntaxKind5["BigIntLiteral"] = 10] = "BigIntLiteral";
    SyntaxKind5[SyntaxKind5["StringLiteral"] = 11] = "StringLiteral";
    SyntaxKind5[SyntaxKind5["JsxText"] = 12] = "JsxText";
    SyntaxKind5[SyntaxKind5["JsxTextAllWhiteSpaces"] = 13] = "JsxTextAllWhiteSpaces";
    SyntaxKind5[SyntaxKind5["RegularExpressionLiteral"] = 14] = "RegularExpressionLiteral";
    SyntaxKind5[SyntaxKind5["NoSubstitutionTemplateLiteral"] = 15] = "NoSubstitutionTemplateLiteral";
    SyntaxKind5[SyntaxKind5["TemplateHead"] = 16] = "TemplateHead";
    SyntaxKind5[SyntaxKind5["TemplateMiddle"] = 17] = "TemplateMiddle";
    SyntaxKind5[SyntaxKind5["TemplateTail"] = 18] = "TemplateTail";
    SyntaxKind5[SyntaxKind5["OpenBraceToken"] = 19] = "OpenBraceToken";
    SyntaxKind5[SyntaxKind5["CloseBraceToken"] = 20] = "CloseBraceToken";
    SyntaxKind5[SyntaxKind5["OpenParenToken"] = 21] = "OpenParenToken";
    SyntaxKind5[SyntaxKind5["CloseParenToken"] = 22] = "CloseParenToken";
    SyntaxKind5[SyntaxKind5["OpenBracketToken"] = 23] = "OpenBracketToken";
    SyntaxKind5[SyntaxKind5["CloseBracketToken"] = 24] = "CloseBracketToken";
    SyntaxKind5[SyntaxKind5["DotToken"] = 25] = "DotToken";
    SyntaxKind5[SyntaxKind5["DotDotDotToken"] = 26] = "DotDotDotToken";
    SyntaxKind5[SyntaxKind5["SemicolonToken"] = 27] = "SemicolonToken";
    SyntaxKind5[SyntaxKind5["CommaToken"] = 28] = "CommaToken";
    SyntaxKind5[SyntaxKind5["QuestionDotToken"] = 29] = "QuestionDotToken";
    SyntaxKind5[SyntaxKind5["LessThanToken"] = 30] = "LessThanToken";
    SyntaxKind5[SyntaxKind5["LessThanSlashToken"] = 31] = "LessThanSlashToken";
    SyntaxKind5[SyntaxKind5["GreaterThanToken"] = 32] = "GreaterThanToken";
    SyntaxKind5[SyntaxKind5["LessThanEqualsToken"] = 33] = "LessThanEqualsToken";
    SyntaxKind5[SyntaxKind5["GreaterThanEqualsToken"] = 34] = "GreaterThanEqualsToken";
    SyntaxKind5[SyntaxKind5["EqualsEqualsToken"] = 35] = "EqualsEqualsToken";
    SyntaxKind5[SyntaxKind5["ExclamationEqualsToken"] = 36] = "ExclamationEqualsToken";
    SyntaxKind5[SyntaxKind5["EqualsEqualsEqualsToken"] = 37] = "EqualsEqualsEqualsToken";
    SyntaxKind5[SyntaxKind5["ExclamationEqualsEqualsToken"] = 38] = "ExclamationEqualsEqualsToken";
    SyntaxKind5[SyntaxKind5["EqualsGreaterThanToken"] = 39] = "EqualsGreaterThanToken";
    SyntaxKind5[SyntaxKind5["PlusToken"] = 40] = "PlusToken";
    SyntaxKind5[SyntaxKind5["MinusToken"] = 41] = "MinusToken";
    SyntaxKind5[SyntaxKind5["AsteriskToken"] = 42] = "AsteriskToken";
    SyntaxKind5[SyntaxKind5["AsteriskAsteriskToken"] = 43] = "AsteriskAsteriskToken";
    SyntaxKind5[SyntaxKind5["SlashToken"] = 44] = "SlashToken";
    SyntaxKind5[SyntaxKind5["PercentToken"] = 45] = "PercentToken";
    SyntaxKind5[SyntaxKind5["PlusPlusToken"] = 46] = "PlusPlusToken";
    SyntaxKind5[SyntaxKind5["MinusMinusToken"] = 47] = "MinusMinusToken";
    SyntaxKind5[SyntaxKind5["LessThanLessThanToken"] = 48] = "LessThanLessThanToken";
    SyntaxKind5[SyntaxKind5["GreaterThanGreaterThanToken"] = 49] = "GreaterThanGreaterThanToken";
    SyntaxKind5[SyntaxKind5["GreaterThanGreaterThanGreaterThanToken"] = 50] = "GreaterThanGreaterThanGreaterThanToken";
    SyntaxKind5[SyntaxKind5["AmpersandToken"] = 51] = "AmpersandToken";
    SyntaxKind5[SyntaxKind5["BarToken"] = 52] = "BarToken";
    SyntaxKind5[SyntaxKind5["CaretToken"] = 53] = "CaretToken";
    SyntaxKind5[SyntaxKind5["ExclamationToken"] = 54] = "ExclamationToken";
    SyntaxKind5[SyntaxKind5["TildeToken"] = 55] = "TildeToken";
    SyntaxKind5[SyntaxKind5["AmpersandAmpersandToken"] = 56] = "AmpersandAmpersandToken";
    SyntaxKind5[SyntaxKind5["BarBarToken"] = 57] = "BarBarToken";
    SyntaxKind5[SyntaxKind5["QuestionToken"] = 58] = "QuestionToken";
    SyntaxKind5[SyntaxKind5["ColonToken"] = 59] = "ColonToken";
    SyntaxKind5[SyntaxKind5["AtToken"] = 60] = "AtToken";
    SyntaxKind5[SyntaxKind5["QuestionQuestionToken"] = 61] = "QuestionQuestionToken";
    SyntaxKind5[SyntaxKind5["BacktickToken"] = 62] = "BacktickToken";
    SyntaxKind5[SyntaxKind5["HashToken"] = 63] = "HashToken";
    SyntaxKind5[SyntaxKind5["EqualsToken"] = 64] = "EqualsToken";
    SyntaxKind5[SyntaxKind5["PlusEqualsToken"] = 65] = "PlusEqualsToken";
    SyntaxKind5[SyntaxKind5["MinusEqualsToken"] = 66] = "MinusEqualsToken";
    SyntaxKind5[SyntaxKind5["AsteriskEqualsToken"] = 67] = "AsteriskEqualsToken";
    SyntaxKind5[SyntaxKind5["AsteriskAsteriskEqualsToken"] = 68] = "AsteriskAsteriskEqualsToken";
    SyntaxKind5[SyntaxKind5["SlashEqualsToken"] = 69] = "SlashEqualsToken";
    SyntaxKind5[SyntaxKind5["PercentEqualsToken"] = 70] = "PercentEqualsToken";
    SyntaxKind5[SyntaxKind5["LessThanLessThanEqualsToken"] = 71] = "LessThanLessThanEqualsToken";
    SyntaxKind5[SyntaxKind5["GreaterThanGreaterThanEqualsToken"] = 72] = "GreaterThanGreaterThanEqualsToken";
    SyntaxKind5[SyntaxKind5["GreaterThanGreaterThanGreaterThanEqualsToken"] = 73] = "GreaterThanGreaterThanGreaterThanEqualsToken";
    SyntaxKind5[SyntaxKind5["AmpersandEqualsToken"] = 74] = "AmpersandEqualsToken";
    SyntaxKind5[SyntaxKind5["BarEqualsToken"] = 75] = "BarEqualsToken";
    SyntaxKind5[SyntaxKind5["BarBarEqualsToken"] = 76] = "BarBarEqualsToken";
    SyntaxKind5[SyntaxKind5["AmpersandAmpersandEqualsToken"] = 77] = "AmpersandAmpersandEqualsToken";
    SyntaxKind5[SyntaxKind5["QuestionQuestionEqualsToken"] = 78] = "QuestionQuestionEqualsToken";
    SyntaxKind5[SyntaxKind5["CaretEqualsToken"] = 79] = "CaretEqualsToken";
    SyntaxKind5[SyntaxKind5["Identifier"] = 80] = "Identifier";
    SyntaxKind5[SyntaxKind5["PrivateIdentifier"] = 81] = "PrivateIdentifier";
    SyntaxKind5[SyntaxKind5["JSDocCommentTextToken"] = 82] = "JSDocCommentTextToken";
    SyntaxKind5[SyntaxKind5["BreakKeyword"] = 83] = "BreakKeyword";
    SyntaxKind5[SyntaxKind5["CaseKeyword"] = 84] = "CaseKeyword";
    SyntaxKind5[SyntaxKind5["CatchKeyword"] = 85] = "CatchKeyword";
    SyntaxKind5[SyntaxKind5["ClassKeyword"] = 86] = "ClassKeyword";
    SyntaxKind5[SyntaxKind5["ConstKeyword"] = 87] = "ConstKeyword";
    SyntaxKind5[SyntaxKind5["ContinueKeyword"] = 88] = "ContinueKeyword";
    SyntaxKind5[SyntaxKind5["DebuggerKeyword"] = 89] = "DebuggerKeyword";
    SyntaxKind5[SyntaxKind5["DefaultKeyword"] = 90] = "DefaultKeyword";
    SyntaxKind5[SyntaxKind5["DeleteKeyword"] = 91] = "DeleteKeyword";
    SyntaxKind5[SyntaxKind5["DoKeyword"] = 92] = "DoKeyword";
    SyntaxKind5[SyntaxKind5["ElseKeyword"] = 93] = "ElseKeyword";
    SyntaxKind5[SyntaxKind5["EnumKeyword"] = 94] = "EnumKeyword";
    SyntaxKind5[SyntaxKind5["ExportKeyword"] = 95] = "ExportKeyword";
    SyntaxKind5[SyntaxKind5["ExtendsKeyword"] = 96] = "ExtendsKeyword";
    SyntaxKind5[SyntaxKind5["FalseKeyword"] = 97] = "FalseKeyword";
    SyntaxKind5[SyntaxKind5["FinallyKeyword"] = 98] = "FinallyKeyword";
    SyntaxKind5[SyntaxKind5["ForKeyword"] = 99] = "ForKeyword";
    SyntaxKind5[SyntaxKind5["FunctionKeyword"] = 100] = "FunctionKeyword";
    SyntaxKind5[SyntaxKind5["IfKeyword"] = 101] = "IfKeyword";
    SyntaxKind5[SyntaxKind5["ImportKeyword"] = 102] = "ImportKeyword";
    SyntaxKind5[SyntaxKind5["InKeyword"] = 103] = "InKeyword";
    SyntaxKind5[SyntaxKind5["InstanceOfKeyword"] = 104] = "InstanceOfKeyword";
    SyntaxKind5[SyntaxKind5["NewKeyword"] = 105] = "NewKeyword";
    SyntaxKind5[SyntaxKind5["NullKeyword"] = 106] = "NullKeyword";
    SyntaxKind5[SyntaxKind5["ReturnKeyword"] = 107] = "ReturnKeyword";
    SyntaxKind5[SyntaxKind5["SuperKeyword"] = 108] = "SuperKeyword";
    SyntaxKind5[SyntaxKind5["SwitchKeyword"] = 109] = "SwitchKeyword";
    SyntaxKind5[SyntaxKind5["ThisKeyword"] = 110] = "ThisKeyword";
    SyntaxKind5[SyntaxKind5["ThrowKeyword"] = 111] = "ThrowKeyword";
    SyntaxKind5[SyntaxKind5["TrueKeyword"] = 112] = "TrueKeyword";
    SyntaxKind5[SyntaxKind5["TryKeyword"] = 113] = "TryKeyword";
    SyntaxKind5[SyntaxKind5["TypeOfKeyword"] = 114] = "TypeOfKeyword";
    SyntaxKind5[SyntaxKind5["VarKeyword"] = 115] = "VarKeyword";
    SyntaxKind5[SyntaxKind5["VoidKeyword"] = 116] = "VoidKeyword";
    SyntaxKind5[SyntaxKind5["WhileKeyword"] = 117] = "WhileKeyword";
    SyntaxKind5[SyntaxKind5["WithKeyword"] = 118] = "WithKeyword";
    SyntaxKind5[SyntaxKind5["ImplementsKeyword"] = 119] = "ImplementsKeyword";
    SyntaxKind5[SyntaxKind5["InterfaceKeyword"] = 120] = "InterfaceKeyword";
    SyntaxKind5[SyntaxKind5["LetKeyword"] = 121] = "LetKeyword";
    SyntaxKind5[SyntaxKind5["PackageKeyword"] = 122] = "PackageKeyword";
    SyntaxKind5[SyntaxKind5["PrivateKeyword"] = 123] = "PrivateKeyword";
    SyntaxKind5[SyntaxKind5["ProtectedKeyword"] = 124] = "ProtectedKeyword";
    SyntaxKind5[SyntaxKind5["PublicKeyword"] = 125] = "PublicKeyword";
    SyntaxKind5[SyntaxKind5["StaticKeyword"] = 126] = "StaticKeyword";
    SyntaxKind5[SyntaxKind5["YieldKeyword"] = 127] = "YieldKeyword";
    SyntaxKind5[SyntaxKind5["AbstractKeyword"] = 128] = "AbstractKeyword";
    SyntaxKind5[SyntaxKind5["AccessorKeyword"] = 129] = "AccessorKeyword";
    SyntaxKind5[SyntaxKind5["AsKeyword"] = 130] = "AsKeyword";
    SyntaxKind5[SyntaxKind5["AssertsKeyword"] = 131] = "AssertsKeyword";
    SyntaxKind5[SyntaxKind5["AssertKeyword"] = 132] = "AssertKeyword";
    SyntaxKind5[SyntaxKind5["AnyKeyword"] = 133] = "AnyKeyword";
    SyntaxKind5[SyntaxKind5["AsyncKeyword"] = 134] = "AsyncKeyword";
    SyntaxKind5[SyntaxKind5["AwaitKeyword"] = 135] = "AwaitKeyword";
    SyntaxKind5[SyntaxKind5["BooleanKeyword"] = 136] = "BooleanKeyword";
    SyntaxKind5[SyntaxKind5["ConstructorKeyword"] = 137] = "ConstructorKeyword";
    SyntaxKind5[SyntaxKind5["DeclareKeyword"] = 138] = "DeclareKeyword";
    SyntaxKind5[SyntaxKind5["GetKeyword"] = 139] = "GetKeyword";
    SyntaxKind5[SyntaxKind5["InferKeyword"] = 140] = "InferKeyword";
    SyntaxKind5[SyntaxKind5["IntrinsicKeyword"] = 141] = "IntrinsicKeyword";
    SyntaxKind5[SyntaxKind5["IsKeyword"] = 142] = "IsKeyword";
    SyntaxKind5[SyntaxKind5["KeyOfKeyword"] = 143] = "KeyOfKeyword";
    SyntaxKind5[SyntaxKind5["ModuleKeyword"] = 144] = "ModuleKeyword";
    SyntaxKind5[SyntaxKind5["NamespaceKeyword"] = 145] = "NamespaceKeyword";
    SyntaxKind5[SyntaxKind5["NeverKeyword"] = 146] = "NeverKeyword";
    SyntaxKind5[SyntaxKind5["OutKeyword"] = 147] = "OutKeyword";
    SyntaxKind5[SyntaxKind5["ReadonlyKeyword"] = 148] = "ReadonlyKeyword";
    SyntaxKind5[SyntaxKind5["RequireKeyword"] = 149] = "RequireKeyword";
    SyntaxKind5[SyntaxKind5["NumberKeyword"] = 150] = "NumberKeyword";
    SyntaxKind5[SyntaxKind5["ObjectKeyword"] = 151] = "ObjectKeyword";
    SyntaxKind5[SyntaxKind5["SatisfiesKeyword"] = 152] = "SatisfiesKeyword";
    SyntaxKind5[SyntaxKind5["SetKeyword"] = 153] = "SetKeyword";
    SyntaxKind5[SyntaxKind5["StringKeyword"] = 154] = "StringKeyword";
    SyntaxKind5[SyntaxKind5["SymbolKeyword"] = 155] = "SymbolKeyword";
    SyntaxKind5[SyntaxKind5["TypeKeyword"] = 156] = "TypeKeyword";
    SyntaxKind5[SyntaxKind5["UndefinedKeyword"] = 157] = "UndefinedKeyword";
    SyntaxKind5[SyntaxKind5["UniqueKeyword"] = 158] = "UniqueKeyword";
    SyntaxKind5[SyntaxKind5["UnknownKeyword"] = 159] = "UnknownKeyword";
    SyntaxKind5[SyntaxKind5["UsingKeyword"] = 160] = "UsingKeyword";
    SyntaxKind5[SyntaxKind5["FromKeyword"] = 161] = "FromKeyword";
    SyntaxKind5[SyntaxKind5["GlobalKeyword"] = 162] = "GlobalKeyword";
    SyntaxKind5[SyntaxKind5["BigIntKeyword"] = 163] = "BigIntKeyword";
    SyntaxKind5[SyntaxKind5["OverrideKeyword"] = 164] = "OverrideKeyword";
    SyntaxKind5[SyntaxKind5["OfKeyword"] = 165] = "OfKeyword";
    SyntaxKind5[SyntaxKind5["QualifiedName"] = 166] = "QualifiedName";
    SyntaxKind5[SyntaxKind5["ComputedPropertyName"] = 167] = "ComputedPropertyName";
    SyntaxKind5[SyntaxKind5["TypeParameter"] = 168] = "TypeParameter";
    SyntaxKind5[SyntaxKind5["Parameter"] = 169] = "Parameter";
    SyntaxKind5[SyntaxKind5["Decorator"] = 170] = "Decorator";
    SyntaxKind5[SyntaxKind5["PropertySignature"] = 171] = "PropertySignature";
    SyntaxKind5[SyntaxKind5["PropertyDeclaration"] = 172] = "PropertyDeclaration";
    SyntaxKind5[SyntaxKind5["MethodSignature"] = 173] = "MethodSignature";
    SyntaxKind5[SyntaxKind5["MethodDeclaration"] = 174] = "MethodDeclaration";
    SyntaxKind5[SyntaxKind5["ClassStaticBlockDeclaration"] = 175] = "ClassStaticBlockDeclaration";
    SyntaxKind5[SyntaxKind5["Constructor"] = 176] = "Constructor";
    SyntaxKind5[SyntaxKind5["GetAccessor"] = 177] = "GetAccessor";
    SyntaxKind5[SyntaxKind5["SetAccessor"] = 178] = "SetAccessor";
    SyntaxKind5[SyntaxKind5["CallSignature"] = 179] = "CallSignature";
    SyntaxKind5[SyntaxKind5["ConstructSignature"] = 180] = "ConstructSignature";
    SyntaxKind5[SyntaxKind5["IndexSignature"] = 181] = "IndexSignature";
    SyntaxKind5[SyntaxKind5["TypePredicate"] = 182] = "TypePredicate";
    SyntaxKind5[SyntaxKind5["TypeReference"] = 183] = "TypeReference";
    SyntaxKind5[SyntaxKind5["FunctionType"] = 184] = "FunctionType";
    SyntaxKind5[SyntaxKind5["ConstructorType"] = 185] = "ConstructorType";
    SyntaxKind5[SyntaxKind5["TypeQuery"] = 186] = "TypeQuery";
    SyntaxKind5[SyntaxKind5["TypeLiteral"] = 187] = "TypeLiteral";
    SyntaxKind5[SyntaxKind5["ArrayType"] = 188] = "ArrayType";
    SyntaxKind5[SyntaxKind5["TupleType"] = 189] = "TupleType";
    SyntaxKind5[SyntaxKind5["OptionalType"] = 190] = "OptionalType";
    SyntaxKind5[SyntaxKind5["RestType"] = 191] = "RestType";
    SyntaxKind5[SyntaxKind5["UnionType"] = 192] = "UnionType";
    SyntaxKind5[SyntaxKind5["IntersectionType"] = 193] = "IntersectionType";
    SyntaxKind5[SyntaxKind5["ConditionalType"] = 194] = "ConditionalType";
    SyntaxKind5[SyntaxKind5["InferType"] = 195] = "InferType";
    SyntaxKind5[SyntaxKind5["ParenthesizedType"] = 196] = "ParenthesizedType";
    SyntaxKind5[SyntaxKind5["ThisType"] = 197] = "ThisType";
    SyntaxKind5[SyntaxKind5["TypeOperator"] = 198] = "TypeOperator";
    SyntaxKind5[SyntaxKind5["IndexedAccessType"] = 199] = "IndexedAccessType";
    SyntaxKind5[SyntaxKind5["MappedType"] = 200] = "MappedType";
    SyntaxKind5[SyntaxKind5["LiteralType"] = 201] = "LiteralType";
    SyntaxKind5[SyntaxKind5["NamedTupleMember"] = 202] = "NamedTupleMember";
    SyntaxKind5[SyntaxKind5["TemplateLiteralType"] = 203] = "TemplateLiteralType";
    SyntaxKind5[SyntaxKind5["TemplateLiteralTypeSpan"] = 204] = "TemplateLiteralTypeSpan";
    SyntaxKind5[SyntaxKind5["ImportType"] = 205] = "ImportType";
    SyntaxKind5[SyntaxKind5["ObjectBindingPattern"] = 206] = "ObjectBindingPattern";
    SyntaxKind5[SyntaxKind5["ArrayBindingPattern"] = 207] = "ArrayBindingPattern";
    SyntaxKind5[SyntaxKind5["BindingElement"] = 208] = "BindingElement";
    SyntaxKind5[SyntaxKind5["ArrayLiteralExpression"] = 209] = "ArrayLiteralExpression";
    SyntaxKind5[SyntaxKind5["ObjectLiteralExpression"] = 210] = "ObjectLiteralExpression";
    SyntaxKind5[SyntaxKind5["PropertyAccessExpression"] = 211] = "PropertyAccessExpression";
    SyntaxKind5[SyntaxKind5["ElementAccessExpression"] = 212] = "ElementAccessExpression";
    SyntaxKind5[SyntaxKind5["CallExpression"] = 213] = "CallExpression";
    SyntaxKind5[SyntaxKind5["NewExpression"] = 214] = "NewExpression";
    SyntaxKind5[SyntaxKind5["TaggedTemplateExpression"] = 215] = "TaggedTemplateExpression";
    SyntaxKind5[SyntaxKind5["TypeAssertionExpression"] = 216] = "TypeAssertionExpression";
    SyntaxKind5[SyntaxKind5["ParenthesizedExpression"] = 217] = "ParenthesizedExpression";
    SyntaxKind5[SyntaxKind5["FunctionExpression"] = 218] = "FunctionExpression";
    SyntaxKind5[SyntaxKind5["ArrowFunction"] = 219] = "ArrowFunction";
    SyntaxKind5[SyntaxKind5["DeleteExpression"] = 220] = "DeleteExpression";
    SyntaxKind5[SyntaxKind5["TypeOfExpression"] = 221] = "TypeOfExpression";
    SyntaxKind5[SyntaxKind5["VoidExpression"] = 222] = "VoidExpression";
    SyntaxKind5[SyntaxKind5["AwaitExpression"] = 223] = "AwaitExpression";
    SyntaxKind5[SyntaxKind5["PrefixUnaryExpression"] = 224] = "PrefixUnaryExpression";
    SyntaxKind5[SyntaxKind5["PostfixUnaryExpression"] = 225] = "PostfixUnaryExpression";
    SyntaxKind5[SyntaxKind5["BinaryExpression"] = 226] = "BinaryExpression";
    SyntaxKind5[SyntaxKind5["ConditionalExpression"] = 227] = "ConditionalExpression";
    SyntaxKind5[SyntaxKind5["TemplateExpression"] = 228] = "TemplateExpression";
    SyntaxKind5[SyntaxKind5["YieldExpression"] = 229] = "YieldExpression";
    SyntaxKind5[SyntaxKind5["SpreadElement"] = 230] = "SpreadElement";
    SyntaxKind5[SyntaxKind5["ClassExpression"] = 231] = "ClassExpression";
    SyntaxKind5[SyntaxKind5["OmittedExpression"] = 232] = "OmittedExpression";
    SyntaxKind5[SyntaxKind5["ExpressionWithTypeArguments"] = 233] = "ExpressionWithTypeArguments";
    SyntaxKind5[SyntaxKind5["AsExpression"] = 234] = "AsExpression";
    SyntaxKind5[SyntaxKind5["NonNullExpression"] = 235] = "NonNullExpression";
    SyntaxKind5[SyntaxKind5["MetaProperty"] = 236] = "MetaProperty";
    SyntaxKind5[SyntaxKind5["SyntheticExpression"] = 237] = "SyntheticExpression";
    SyntaxKind5[SyntaxKind5["SatisfiesExpression"] = 238] = "SatisfiesExpression";
    SyntaxKind5[SyntaxKind5["TemplateSpan"] = 239] = "TemplateSpan";
    SyntaxKind5[SyntaxKind5["SemicolonClassElement"] = 240] = "SemicolonClassElement";
    SyntaxKind5[SyntaxKind5["Block"] = 241] = "Block";
    SyntaxKind5[SyntaxKind5["EmptyStatement"] = 242] = "EmptyStatement";
    SyntaxKind5[SyntaxKind5["VariableStatement"] = 243] = "VariableStatement";
    SyntaxKind5[SyntaxKind5["ExpressionStatement"] = 244] = "ExpressionStatement";
    SyntaxKind5[SyntaxKind5["IfStatement"] = 245] = "IfStatement";
    SyntaxKind5[SyntaxKind5["DoStatement"] = 246] = "DoStatement";
    SyntaxKind5[SyntaxKind5["WhileStatement"] = 247] = "WhileStatement";
    SyntaxKind5[SyntaxKind5["ForStatement"] = 248] = "ForStatement";
    SyntaxKind5[SyntaxKind5["ForInStatement"] = 249] = "ForInStatement";
    SyntaxKind5[SyntaxKind5["ForOfStatement"] = 250] = "ForOfStatement";
    SyntaxKind5[SyntaxKind5["ContinueStatement"] = 251] = "ContinueStatement";
    SyntaxKind5[SyntaxKind5["BreakStatement"] = 252] = "BreakStatement";
    SyntaxKind5[SyntaxKind5["ReturnStatement"] = 253] = "ReturnStatement";
    SyntaxKind5[SyntaxKind5["WithStatement"] = 254] = "WithStatement";
    SyntaxKind5[SyntaxKind5["SwitchStatement"] = 255] = "SwitchStatement";
    SyntaxKind5[SyntaxKind5["LabeledStatement"] = 256] = "LabeledStatement";
    SyntaxKind5[SyntaxKind5["ThrowStatement"] = 257] = "ThrowStatement";
    SyntaxKind5[SyntaxKind5["TryStatement"] = 258] = "TryStatement";
    SyntaxKind5[SyntaxKind5["DebuggerStatement"] = 259] = "DebuggerStatement";
    SyntaxKind5[SyntaxKind5["VariableDeclaration"] = 260] = "VariableDeclaration";
    SyntaxKind5[SyntaxKind5["VariableDeclarationList"] = 261] = "VariableDeclarationList";
    SyntaxKind5[SyntaxKind5["FunctionDeclaration"] = 262] = "FunctionDeclaration";
    SyntaxKind5[SyntaxKind5["ClassDeclaration"] = 263] = "ClassDeclaration";
    SyntaxKind5[SyntaxKind5["InterfaceDeclaration"] = 264] = "InterfaceDeclaration";
    SyntaxKind5[SyntaxKind5["TypeAliasDeclaration"] = 265] = "TypeAliasDeclaration";
    SyntaxKind5[SyntaxKind5["EnumDeclaration"] = 266] = "EnumDeclaration";
    SyntaxKind5[SyntaxKind5["ModuleDeclaration"] = 267] = "ModuleDeclaration";
    SyntaxKind5[SyntaxKind5["ModuleBlock"] = 268] = "ModuleBlock";
    SyntaxKind5[SyntaxKind5["CaseBlock"] = 269] = "CaseBlock";
    SyntaxKind5[SyntaxKind5["NamespaceExportDeclaration"] = 270] = "NamespaceExportDeclaration";
    SyntaxKind5[SyntaxKind5["ImportEqualsDeclaration"] = 271] = "ImportEqualsDeclaration";
    SyntaxKind5[SyntaxKind5["ImportDeclaration"] = 272] = "ImportDeclaration";
    SyntaxKind5[SyntaxKind5["ImportClause"] = 273] = "ImportClause";
    SyntaxKind5[SyntaxKind5["NamespaceImport"] = 274] = "NamespaceImport";
    SyntaxKind5[SyntaxKind5["NamedImports"] = 275] = "NamedImports";
    SyntaxKind5[SyntaxKind5["ImportSpecifier"] = 276] = "ImportSpecifier";
    SyntaxKind5[SyntaxKind5["ExportAssignment"] = 277] = "ExportAssignment";
    SyntaxKind5[SyntaxKind5["ExportDeclaration"] = 278] = "ExportDeclaration";
    SyntaxKind5[SyntaxKind5["NamedExports"] = 279] = "NamedExports";
    SyntaxKind5[SyntaxKind5["NamespaceExport"] = 280] = "NamespaceExport";
    SyntaxKind5[SyntaxKind5["ExportSpecifier"] = 281] = "ExportSpecifier";
    SyntaxKind5[SyntaxKind5["MissingDeclaration"] = 282] = "MissingDeclaration";
    SyntaxKind5[SyntaxKind5["ExternalModuleReference"] = 283] = "ExternalModuleReference";
    SyntaxKind5[SyntaxKind5["JsxElement"] = 284] = "JsxElement";
    SyntaxKind5[SyntaxKind5["JsxSelfClosingElement"] = 285] = "JsxSelfClosingElement";
    SyntaxKind5[SyntaxKind5["JsxOpeningElement"] = 286] = "JsxOpeningElement";
    SyntaxKind5[SyntaxKind5["JsxClosingElement"] = 287] = "JsxClosingElement";
    SyntaxKind5[SyntaxKind5["JsxFragment"] = 288] = "JsxFragment";
    SyntaxKind5[SyntaxKind5["JsxOpeningFragment"] = 289] = "JsxOpeningFragment";
    SyntaxKind5[SyntaxKind5["JsxClosingFragment"] = 290] = "JsxClosingFragment";
    SyntaxKind5[SyntaxKind5["JsxAttribute"] = 291] = "JsxAttribute";
    SyntaxKind5[SyntaxKind5["JsxAttributes"] = 292] = "JsxAttributes";
    SyntaxKind5[SyntaxKind5["JsxSpreadAttribute"] = 293] = "JsxSpreadAttribute";
    SyntaxKind5[SyntaxKind5["JsxExpression"] = 294] = "JsxExpression";
    SyntaxKind5[SyntaxKind5["JsxNamespacedName"] = 295] = "JsxNamespacedName";
    SyntaxKind5[SyntaxKind5["CaseClause"] = 296] = "CaseClause";
    SyntaxKind5[SyntaxKind5["DefaultClause"] = 297] = "DefaultClause";
    SyntaxKind5[SyntaxKind5["HeritageClause"] = 298] = "HeritageClause";
    SyntaxKind5[SyntaxKind5["CatchClause"] = 299] = "CatchClause";
    SyntaxKind5[SyntaxKind5["ImportAttributes"] = 300] = "ImportAttributes";
    SyntaxKind5[SyntaxKind5["ImportAttribute"] = 301] = "ImportAttribute";
    SyntaxKind5[SyntaxKind5["AssertClause"] = 300 /* ImportAttributes */] = "AssertClause";
    SyntaxKind5[SyntaxKind5["AssertEntry"] = 301 /* ImportAttribute */] = "AssertEntry";
    SyntaxKind5[SyntaxKind5["ImportTypeAssertionContainer"] = 302] = "ImportTypeAssertionContainer";
    SyntaxKind5[SyntaxKind5["PropertyAssignment"] = 303] = "PropertyAssignment";
    SyntaxKind5[SyntaxKind5["ShorthandPropertyAssignment"] = 304] = "ShorthandPropertyAssignment";
    SyntaxKind5[SyntaxKind5["SpreadAssignment"] = 305] = "SpreadAssignment";
    SyntaxKind5[SyntaxKind5["EnumMember"] = 306] = "EnumMember";
    SyntaxKind5[SyntaxKind5["SourceFile"] = 307] = "SourceFile";
    SyntaxKind5[SyntaxKind5["Bundle"] = 308] = "Bundle";
    SyntaxKind5[SyntaxKind5["JSDocTypeExpression"] = 309] = "JSDocTypeExpression";
    SyntaxKind5[SyntaxKind5["JSDocNameReference"] = 310] = "JSDocNameReference";
    SyntaxKind5[SyntaxKind5["JSDocMemberName"] = 311] = "JSDocMemberName";
    SyntaxKind5[SyntaxKind5["JSDocAllType"] = 312] = "JSDocAllType";
    SyntaxKind5[SyntaxKind5["JSDocUnknownType"] = 313] = "JSDocUnknownType";
    SyntaxKind5[SyntaxKind5["JSDocNullableType"] = 314] = "JSDocNullableType";
    SyntaxKind5[SyntaxKind5["JSDocNonNullableType"] = 315] = "JSDocNonNullableType";
    SyntaxKind5[SyntaxKind5["JSDocOptionalType"] = 316] = "JSDocOptionalType";
    SyntaxKind5[SyntaxKind5["JSDocFunctionType"] = 317] = "JSDocFunctionType";
    SyntaxKind5[SyntaxKind5["JSDocVariadicType"] = 318] = "JSDocVariadicType";
    SyntaxKind5[SyntaxKind5["JSDocNamepathType"] = 319] = "JSDocNamepathType";
    SyntaxKind5[SyntaxKind5["JSDoc"] = 320] = "JSDoc";
    SyntaxKind5[SyntaxKind5["JSDocComment"] = 320 /* JSDoc */] = "JSDocComment";
    SyntaxKind5[SyntaxKind5["JSDocText"] = 321] = "JSDocText";
    SyntaxKind5[SyntaxKind5["JSDocTypeLiteral"] = 322] = "JSDocTypeLiteral";
    SyntaxKind5[SyntaxKind5["JSDocSignature"] = 323] = "JSDocSignature";
    SyntaxKind5[SyntaxKind5["JSDocLink"] = 324] = "JSDocLink";
    SyntaxKind5[SyntaxKind5["JSDocLinkCode"] = 325] = "JSDocLinkCode";
    SyntaxKind5[SyntaxKind5["JSDocLinkPlain"] = 326] = "JSDocLinkPlain";
    SyntaxKind5[SyntaxKind5["JSDocTag"] = 327] = "JSDocTag";
    SyntaxKind5[SyntaxKind5["JSDocAugmentsTag"] = 328] = "JSDocAugmentsTag";
    SyntaxKind5[SyntaxKind5["JSDocImplementsTag"] = 329] = "JSDocImplementsTag";
    SyntaxKind5[SyntaxKind5["JSDocAuthorTag"] = 330] = "JSDocAuthorTag";
    SyntaxKind5[SyntaxKind5["JSDocDeprecatedTag"] = 331] = "JSDocDeprecatedTag";
    SyntaxKind5[SyntaxKind5["JSDocClassTag"] = 332] = "JSDocClassTag";
    SyntaxKind5[SyntaxKind5["JSDocPublicTag"] = 333] = "JSDocPublicTag";
    SyntaxKind5[SyntaxKind5["JSDocPrivateTag"] = 334] = "JSDocPrivateTag";
    SyntaxKind5[SyntaxKind5["JSDocProtectedTag"] = 335] = "JSDocProtectedTag";
    SyntaxKind5[SyntaxKind5["JSDocReadonlyTag"] = 336] = "JSDocReadonlyTag";
    SyntaxKind5[SyntaxKind5["JSDocOverrideTag"] = 337] = "JSDocOverrideTag";
    SyntaxKind5[SyntaxKind5["JSDocCallbackTag"] = 338] = "JSDocCallbackTag";
    SyntaxKind5[SyntaxKind5["JSDocOverloadTag"] = 339] = "JSDocOverloadTag";
    SyntaxKind5[SyntaxKind5["JSDocEnumTag"] = 340] = "JSDocEnumTag";
    SyntaxKind5[SyntaxKind5["JSDocParameterTag"] = 341] = "JSDocParameterTag";
    SyntaxKind5[SyntaxKind5["JSDocReturnTag"] = 342] = "JSDocReturnTag";
    SyntaxKind5[SyntaxKind5["JSDocThisTag"] = 343] = "JSDocThisTag";
    SyntaxKind5[SyntaxKind5["JSDocTypeTag"] = 344] = "JSDocTypeTag";
    SyntaxKind5[SyntaxKind5["JSDocTemplateTag"] = 345] = "JSDocTemplateTag";
    SyntaxKind5[SyntaxKind5["JSDocTypedefTag"] = 346] = "JSDocTypedefTag";
    SyntaxKind5[SyntaxKind5["JSDocSeeTag"] = 347] = "JSDocSeeTag";
    SyntaxKind5[SyntaxKind5["JSDocPropertyTag"] = 348] = "JSDocPropertyTag";
    SyntaxKind5[SyntaxKind5["JSDocThrowsTag"] = 349] = "JSDocThrowsTag";
    SyntaxKind5[SyntaxKind5["JSDocSatisfiesTag"] = 350] = "JSDocSatisfiesTag";
    SyntaxKind5[SyntaxKind5["JSDocImportTag"] = 351] = "JSDocImportTag";
    SyntaxKind5[SyntaxKind5["SyntaxList"] = 352] = "SyntaxList";
    SyntaxKind5[SyntaxKind5["NotEmittedStatement"] = 353] = "NotEmittedStatement";
    SyntaxKind5[SyntaxKind5["NotEmittedTypeElement"] = 354] = "NotEmittedTypeElement";
    SyntaxKind5[SyntaxKind5["PartiallyEmittedExpression"] = 355] = "PartiallyEmittedExpression";
    SyntaxKind5[SyntaxKind5["CommaListExpression"] = 356] = "CommaListExpression";
    SyntaxKind5[SyntaxKind5["SyntheticReferenceExpression"] = 357] = "SyntheticReferenceExpression";
    SyntaxKind5[SyntaxKind5["Count"] = 358] = "Count";
    SyntaxKind5[SyntaxKind5["FirstAssignment"] = 64 /* EqualsToken */] = "FirstAssignment";
    SyntaxKind5[SyntaxKind5["LastAssignment"] = 79 /* CaretEqualsToken */] = "LastAssignment";
    SyntaxKind5[SyntaxKind5["FirstCompoundAssignment"] = 65 /* PlusEqualsToken */] = "FirstCompoundAssignment";
    SyntaxKind5[SyntaxKind5["LastCompoundAssignment"] = 79 /* CaretEqualsToken */] = "LastCompoundAssignment";
    SyntaxKind5[SyntaxKind5["FirstReservedWord"] = 83 /* BreakKeyword */] = "FirstReservedWord";
    SyntaxKind5[SyntaxKind5["LastReservedWord"] = 118 /* WithKeyword */] = "LastReservedWord";
    SyntaxKind5[SyntaxKind5["FirstKeyword"] = 83 /* BreakKeyword */] = "FirstKeyword";
    SyntaxKind5[SyntaxKind5["LastKeyword"] = 165 /* OfKeyword */] = "LastKeyword";
    SyntaxKind5[SyntaxKind5["FirstFutureReservedWord"] = 119 /* ImplementsKeyword */] = "FirstFutureReservedWord";
    SyntaxKind5[SyntaxKind5["LastFutureReservedWord"] = 127 /* YieldKeyword */] = "LastFutureReservedWord";
    SyntaxKind5[SyntaxKind5["FirstTypeNode"] = 182 /* TypePredicate */] = "FirstTypeNode";
    SyntaxKind5[SyntaxKind5["LastTypeNode"] = 205 /* ImportType */] = "LastTypeNode";
    SyntaxKind5[SyntaxKind5["FirstPunctuation"] = 19 /* OpenBraceToken */] = "FirstPunctuation";
    SyntaxKind5[SyntaxKind5["LastPunctuation"] = 79 /* CaretEqualsToken */] = "LastPunctuation";
    SyntaxKind5[SyntaxKind5["FirstToken"] = 0 /* Unknown */] = "FirstToken";
    SyntaxKind5[SyntaxKind5["LastToken"] = 165 /* LastKeyword */] = "LastToken";
    SyntaxKind5[SyntaxKind5["FirstTriviaToken"] = 2 /* SingleLineCommentTrivia */] = "FirstTriviaToken";
    SyntaxKind5[SyntaxKind5["LastTriviaToken"] = 7 /* ConflictMarkerTrivia */] = "LastTriviaToken";
    SyntaxKind5[SyntaxKind5["FirstLiteralToken"] = 9 /* NumericLiteral */] = "FirstLiteralToken";
    SyntaxKind5[SyntaxKind5["LastLiteralToken"] = 15 /* NoSubstitutionTemplateLiteral */] = "LastLiteralToken";
    SyntaxKind5[SyntaxKind5["FirstTemplateToken"] = 15 /* NoSubstitutionTemplateLiteral */] = "FirstTemplateToken";
    SyntaxKind5[SyntaxKind5["LastTemplateToken"] = 18 /* TemplateTail */] = "LastTemplateToken";
    SyntaxKind5[SyntaxKind5["FirstBinaryOperator"] = 30 /* LessThanToken */] = "FirstBinaryOperator";
    SyntaxKind5[SyntaxKind5["LastBinaryOperator"] = 79 /* CaretEqualsToken */] = "LastBinaryOperator";
    SyntaxKind5[SyntaxKind5["FirstStatement"] = 243 /* VariableStatement */] = "FirstStatement";
    SyntaxKind5[SyntaxKind5["LastStatement"] = 259 /* DebuggerStatement */] = "LastStatement";
    SyntaxKind5[SyntaxKind5["FirstNode"] = 166 /* QualifiedName */] = "FirstNode";
    SyntaxKind5[SyntaxKind5["FirstJSDocNode"] = 309 /* JSDocTypeExpression */] = "FirstJSDocNode";
    SyntaxKind5[SyntaxKind5["LastJSDocNode"] = 351 /* JSDocImportTag */] = "LastJSDocNode";
    SyntaxKind5[SyntaxKind5["FirstJSDocTagNode"] = 327 /* JSDocTag */] = "FirstJSDocTagNode";
    SyntaxKind5[SyntaxKind5["LastJSDocTagNode"] = 351 /* JSDocImportTag */] = "LastJSDocTagNode";
    SyntaxKind5[SyntaxKind5["FirstContextualKeyword"] = 128 /* AbstractKeyword */] = "FirstContextualKeyword";
    SyntaxKind5[SyntaxKind5["LastContextualKeyword"] = 165 /* OfKeyword */] = "LastContextualKeyword";
    return SyntaxKind5;
  })(SyntaxKind || {});

// console.log(SyntaxKind)

fs.writeFileSync('syntaxkind.json', JSON.stringify(SyntaxKind, null, 2))